# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

# Form implementation generated from reading ui file '/Users/danylo/Downloads/thrd_ver.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 904)
        MainWindow.setStyleSheet(
            "QFrame {\n" "    background-color: rgb(35, 35, 35);\n" "}\n" ""
        )
        self.main_window = QtWidgets.QWidget(MainWindow)
        self.main_window.setStyleSheet(
            "QWidget {\n" "    background-color: rgb(30, 30, 30);\n" "}\n" ""
        )
        self.main_window.setObjectName("main_window")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.main_window)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_w = QtWidgets.QGridLayout()
        self.main_w.setSpacing(0)
        self.main_w.setObjectName("main_w")
        self.tab_layout = QtWidgets.QGridLayout()
        self.tab_layout.setSpacing(0)
        self.tab_layout.setObjectName("tab_layout")
        self.all_tabs = QtWidgets.QTabWidget(self.main_window)
        self.all_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.all_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.all_tabs.setElideMode(QtCore.Qt.ElideRight)
        self.all_tabs.setUsesScrollButtons(False)
        self.all_tabs.setTabsClosable(False)
        self.all_tabs.setMovable(False)
        self.all_tabs.setTabBarAutoHide(False)
        self.all_tabs.setObjectName("all_tabs")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_right_layout = QtWidgets.QVBoxLayout()
        self.main_right_layout.setContentsMargins(0, -1, 0, 0)
        self.main_right_layout.setSpacing(0)
        self.main_right_layout.setObjectName("main_right_layout")
        self.horizontalFrame_3 = QtWidgets.QFrame(self.main_tab)
        self.horizontalFrame_3.setStyleSheet(
            "QFrame{background-color: rgb(35, 35, 35);}"
        )
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.clear_layout = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.clear_layout.setContentsMargins(-1, 15, 10, 19)
        self.clear_layout.setSpacing(0)
        self.clear_layout.setObjectName("clear_layout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.clear_layout.addItem(spacerItem)
        self.clear_button = QtWidgets.QPushButton(self.horizontalFrame_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70); \n"
            "}"
        )
        self.clear_button.setObjectName("clear_button")
        self.clear_layout.addWidget(self.clear_button)
        self.main_right_layout.addWidget(self.horizontalFrame_3)
        self.receiver_list = QtWidgets.QListWidget(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.receiver_list.setFont(font)
        self.receiver_list.setStyleSheet(
            "QListView {\n"
            "    background-color: rgb(35, 35, 35);\n"
            "}\n"
            "QListView::item {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(45, 45, 45)\n"
            "}\n"
            "\n"
            "QListView::item:selected {\n"
            "    background-color: rgb(40, 40, 40);\n"
            "    color: #FFF; \n"
            "    border-color: rgb(114, 159, 207);\n"
            "}"
        )
        self.receiver_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.receiver_list.setObjectName("receiver_list")
        item = QtWidgets.QListWidgetItem()
        self.receiver_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.receiver_list.addItem(item)
        self.main_right_layout.addWidget(self.receiver_list)
        self.formating_message = QtWidgets.QFrame(self.main_tab)
        self.formating_message.setStyleSheet(
            "QFrame {\n"
            "    border-top: 1px solid rgb(50, 50, 50); \n"
            "    border-bottom: 1px solid rgb(50, 50, 50); \n"
            "    background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.formating_message.setObjectName("formating_message")
        self.message_formating = QtWidgets.QHBoxLayout(self.formating_message)
        self.message_formating.setContentsMargins(12, 5, 0, 5)
        self.message_formating.setSpacing(0)
        self.message_formating.setObjectName("message_formating")
        self.msg_convertor = QtWidgets.QPushButton(self.formating_message)
        self.msg_convertor.setMinimumSize(QtCore.QSize(70, 25))
        self.msg_convertor.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.msg_convertor.setFont(font)
        self.msg_convertor.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-right: 0px; \n"
            "   border-top-left-radius: 5;\n"
            "   border-bottom-left-radius: 5;\n"
            "   padding: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70); \n"
            "   border-right: 0px; \n"
            "}"
        )
        self.msg_convertor.setObjectName("msg_convertor")
        self.message_formating.addWidget(self.msg_convertor)
        self.msg_convertor_v = QtWidgets.QPushButton(self.formating_message)
        self.msg_convertor_v.setMinimumSize(QtCore.QSize(25, 25))
        self.msg_convertor_v.setMaximumSize(QtCore.QSize(25, 25))
        self.msg_convertor_v.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-left: 0px; \n"
            "   border-top-right-radius: 5;\n"
            "   border-bottom-right-radius: 5;\n"
            "   padding: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70);\n"
            "   border-left: 0px;  \n"
            "}"
        )
        self.msg_convertor_v.setObjectName("msg_convertor_v")
        self.message_formating.addWidget(self.msg_convertor_v)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.message_formating.addItem(spacerItem1)
        self.all_button = QtWidgets.QPushButton(self.formating_message)
        self.all_button.setMinimumSize(QtCore.QSize(40, 23))
        self.all_button.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.all_button.setFont(font)
        self.all_button.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(35, 35, 35); \n"
            "   padding: 5px;\n"
            "}"
        )
        self.all_button.setObjectName("all_button")
        self.message_formating.addWidget(self.all_button)
        self.divider_1 = QtWidgets.QPushButton(self.formating_message)
        self.divider_1.setMinimumSize(QtCore.QSize(1, 17))
        self.divider_1.setMaximumSize(QtCore.QSize(1, 17))
        self.divider_1.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(35, 35, 35); \n"
            "   border-left: 1px solid rgb(50, 50, 50); \n"
            "   padding: 5px;\n"
            "}"
        )
        self.divider_1.setText("")
        self.divider_1.setObjectName("divider_1")
        self.message_formating.addWidget(self.divider_1)
        self.received_button = QtWidgets.QPushButton(self.formating_message)
        self.received_button.setMinimumSize(QtCore.QSize(80, 23))
        self.received_button.setMaximumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.received_button.setFont(font)
        self.received_button.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(35, 35, 35); \n"
            "   padding: 5px;\n"
            "}"
        )
        self.received_button.setObjectName("received_button")
        self.message_formating.addWidget(self.received_button)
        self.divider_2 = QtWidgets.QPushButton(self.formating_message)
        self.divider_2.setMinimumSize(QtCore.QSize(1, 17))
        self.divider_2.setMaximumSize(QtCore.QSize(1, 17))
        self.divider_2.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(35, 35, 35); \n"
            "   border-left: 1px solid rgb(50, 50, 50); \n"
            "   padding: 5px;\n"
            "}"
        )
        self.divider_2.setText("")
        self.divider_2.setObjectName("divider_2")
        self.message_formating.addWidget(self.divider_2)
        self.published_button = QtWidgets.QPushButton(self.formating_message)
        self.published_button.setMinimumSize(QtCore.QSize(80, 23))
        self.published_button.setMaximumSize(QtCore.QSize(85, 23))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.published_button.setFont(font)
        self.published_button.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(35, 35, 35); \n"
            "   padding-left: 5px;\n"
            "}"
        )
        self.published_button.setObjectName("published_button")
        self.message_formating.addWidget(self.published_button)
        self.main_right_layout.addWidget(self.formating_message)
        self.receiver_display = QtWidgets.QTextEdit(self.main_tab)
        self.receiver_display.setStyleSheet(
            "QTextEdit {\n"
            " background-color: rgb(27, 27, 27);\n"
            " color: rgb(186, 189, 182);\n"
            "    border-bottom: 1px solid rgb(50, 50, 50); \n"
            "}\n"
            ""
        )
        self.receiver_display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.receiver_display.setObjectName("receiver_display")
        self.main_right_layout.addWidget(self.receiver_display)
        self.gridLayout_2.addLayout(self.main_right_layout, 0, 1, 1, 1)
        self.main_left_layout = QtWidgets.QFrame(self.main_tab)
        self.main_left_layout.setStyleSheet("")
        self.main_left_layout.setObjectName("main_left_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_left_layout)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalFrame_4 = QtWidgets.QFrame(self.main_left_layout)
        self.horizontalFrame_4.setStyleSheet(
            "QFrame {    background-color: rgb(35, 35, 35);}"
        )
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalFrame_4)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_11.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(140, 50, 0);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70); \n"
            "}"
        )
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_5.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalFrame_4)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_12.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70); \n"
            "}"
        )
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalFrame_4)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_15.setMaximumSize(QtCore.QSize(50, 25))
        self.pushButton_15.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-right: 0px; \n"
            "   border-top-left-radius: 5;\n"
            "   border-bottom-left-radius: 5;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70); \n"
            "   border-right: 0px; \n"
            "}"
        )
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_4.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalFrame_4)
        self.pushButton_16.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_16.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_16.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-left: 0px; \n"
            "   border-top-right-radius: 5;\n"
            "   border-bottom-right-radius: 5;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70);\n"
            "   border-left: 0px;  \n"
            "}"
        )
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_4.addWidget(self.pushButton_16)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalFrame_4)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_10.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   border: 1px solid rgb(70, 70, 70); \n"
            "}"
        )
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.verticalLayout_3.addWidget(self.horizontalFrame_4)
        self.clipboard_layout = QtWidgets.QHBoxLayout()
        self.clipboard_layout.setContentsMargins(-1, -1, 1, -1)
        self.clipboard_layout.setSpacing(0)
        self.clipboard_layout.setObjectName("clipboard_layout")
        self.command_items = QtWidgets.QListWidget(self.main_left_layout)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.command_items.sizePolicy().hasHeightForWidth()
        )
        self.command_items.setSizePolicy(sizePolicy)
        self.command_items.setMinimumSize(QtCore.QSize(220, 0))
        self.command_items.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.command_items.setFont(font)
        self.command_items.setStyleSheet(
            "QListView {\n"
            "    border-top: 1px solid rgb(50, 50, 50); \n"
            "    border-bottom: 1px solid rgb(50, 50, 50); \n"
            "    background-color: rgb(35, 35, 35);\n"
            "}\n"
            "\n"
            "QListView::item {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(45, 45, 45);\n"
            "}\n"
            "\n"
            "QListView::item:selected {\n"
            "    background-color: rgb(40, 40, 40);\n"
            "    color: #FFF; \n"
            "    border-color: rgb(114, 159, 207);\n"
            "}"
        )
        self.command_items.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.command_items.setObjectName("command_items")
        item = QtWidgets.QListWidgetItem()
        self.command_items.addItem(item)
        self.clipboard_layout.addWidget(self.command_items)
        self.comand_field = QtWidgets.QTextEdit(self.main_left_layout)
        self.comand_field.setStyleSheet(
            "QTextEdit {\n"
            " background-color: rgb(26, 26, 27);\n"
            " color: rgb(186, 189, 182);\n"
            "    border: 1px solid rgb(50, 50, 50); \n"
            "}\n"
            ""
        )
        self.comand_field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.comand_field.setObjectName("comand_field")
        self.clipboard_layout.addWidget(self.comand_field)
        self.clipboard_layout.setStretch(0, 1)
        self.clipboard_layout.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.clipboard_layout)
        self.gridLayout_2.addWidget(self.main_left_layout, 0, 0, 1, 1)
        self.all_tabs.addTab(self.main_tab, "")
        self.plus_tab = QtWidgets.QWidget()
        self.plus_tab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plus_tab.sizePolicy().hasHeightForWidth())
        self.plus_tab.setSizePolicy(sizePolicy)
        self.plus_tab.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.plus_tab.setStyleSheet("")
        self.plus_tab.setObjectName("plus_tab")
        self.plus_layout = QtWidgets.QGridLayout(self.plus_tab)
        self.plus_layout.setContentsMargins(0, 0, 0, 0)
        self.plus_layout.setSpacing(0)
        self.plus_layout.setObjectName("plus_layout")
        self.scrollArea = QtWidgets.QScrollArea(self.plus_tab)
        self.scrollArea.setStyleSheet("QScrollArea{border: 0px}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 939, 1225))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(100, 20))
        self.label_9.setStyleSheet("QLabel {color: rgb(186, 189, 182);}")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setStyleSheet(
            "QFrame{background-color: rgb(35, 35, 35);   border-radius: 5;   border: 1px solid rgb(50, 50, 50); }\n"
            ""
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(30, 20, 100, 20)
        self.gridLayout_4.setSpacing(15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_4.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_7.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_2.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}"
        )
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_5.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_23.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 9, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_22.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 8, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_6.setStyleSheet(
            "QCheckBox {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_4.addWidget(self.checkBox_6, 8, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "background-color: rgb(35, 35, 35);\n"
            "   padding: 5px;\n"
            "}"
        )
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 3, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_3.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_6.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setStyleSheet(
            "QCheckBox {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 7, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "background-color: rgb(35, 35, 35);\n"
            "   padding: 5px;\n"
            "}"
        )
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 4, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "background-color: rgb(35, 35, 35);\n"
            "   padding: 5px;\n"
            "}"
        )
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 6, 2, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setStyleSheet(
            "QRadioButton {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_10.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setStyleSheet(
            "QRadioButton {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_10.addWidget(self.radioButton)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 9, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.frame)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setMinimumSize(QtCore.QSize(100, 30))
        self.label_24.setMaximumSize(QtCore.QSize(100, 30))
        self.label_24.setStyleSheet("QLabel {color: rgb(186, 189, 182);}\n" "")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.certificates_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.certificates_frame.setStyleSheet(
            "QFrame{background-color: rgb(35, 35, 35);   border-radius: 5;   border: 1px solid rgb(50, 50, 50); }\n"
            ""
        )
        self.certificates_frame.setObjectName("certificates_frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.certificates_frame)
        self.gridLayout_7.setContentsMargins(30, 20, 100, 20)
        self.gridLayout_7.setSpacing(15)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.certificates_frame)
        self.lineEdit_8.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "background-color: rgb(35, 35, 35);\n"
            "   padding: 5px;\n"
            "}"
        )
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_7.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.certificates_frame)
        self.label_25.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_25.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.certificates_frame)
        self.lineEdit_12.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "background-color: rgb(35, 35, 35);\n"
            "   padding: 5px;\n"
            "}"
        )
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_7.addWidget(self.lineEdit_12, 2, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.certificates_frame)
        self.lineEdit_9.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "background-color: rgb(35, 35, 35);\n"
            "   padding: 5px;\n"
            "}"
        )
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_7.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.certificates_frame)
        self.label_26.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_26.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.certificates_frame)
        self.label_27.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_27.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 2, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.certificates_frame)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(100, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 20))
        self.label_8.setStyleSheet("QLabel {color: rgb(186, 189, 182);}")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setStyleSheet(
            "QFrame{background-color: rgb(35, 35, 35);   border-radius: 5;    border: 1px solid rgb(50, 50, 50); }\n"
            ""
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setContentsMargins(30, -1, 100, 20)
        self.gridLayout_6.setSpacing(15)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_16.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_6.addWidget(self.lineEdit_16, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_13.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 3, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setStyleSheet(
            "QCheckBox {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 5, 2, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_15.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_6.addWidget(self.lineEdit_15, 6, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_6.addWidget(self.lineEdit_11, 8, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_14.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_6.addWidget(self.lineEdit_14, 4, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_6.addWidget(self.lineEdit_10, 9, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_18.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 8, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_19.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 9, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_12.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_18.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_6.addWidget(self.lineEdit_18, 0, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_17.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_6.addWidget(self.lineEdit_17, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_15.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_16.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_11.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_10.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_20.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 10, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setStyleSheet(
            "QCheckBox {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_6.addWidget(self.checkBox_2, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_14.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 4, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setStyleSheet(
            "QLineEdit {\n"
            "   color: rgb(186, 189, 182);\n"
            "   border: 1px solid rgb(50, 50, 50); \n"
            "   border-radius: 5;\n"
            "   padding: 5px;\n"
            "background-color: rgb(35, 35, 35);\n"
            "}\n"
            ""
        )
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_6.addWidget(self.lineEdit_7, 7, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_21.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 11, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setStyleSheet("QLabel {color: rgb(186, 189, 182);border: 0px;}")
        self.label_17.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 7, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_4.setStyleSheet(
            "QCheckBox {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_6.addWidget(self.checkBox_4, 11, 2, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_5.setStyleSheet(
            "QCheckBox {color: rgb(186, 189, 182);background-color: rgb(35, 35, 35);}"
        )
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_6.addWidget(self.checkBox_5, 10, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.plus_layout.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.all_tabs.addTab(self.plus_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.all_tabs.addTab(self.settings_tab, "")
        self.info_tab = QtWidgets.QWidget()
        self.info_tab.setObjectName("info_tab")
        self.all_tabs.addTab(self.info_tab, "")
        self.tab_layout.addWidget(self.all_tabs, 0, 0, 1, 1)
        self.main_w.addLayout(self.tab_layout, 1, 0, 1, 1)
        self.header = QtWidgets.QFrame(self.main_window)
        self.header.setStyleSheet(
            "QFrame {\n" "   background-color: rgb(35, 35, 35);\n" "}"
        )
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_14 = QtWidgets.QPushButton(self.header)
        self.pushButton_14.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_14.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_14.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border-radius: 5;\n"
            "   padding-left: 5;\n"
            "   padding-right: 5;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(45, 45, 45);\n"
            "}"
        )
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout.addWidget(self.pushButton_14)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.header)
        self.pushButton_6.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border-top-left-radius: 5;\n"
            "   border-bottom-left-radius: 5;\n"
            "   padding-left: 5;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(45, 45, 45);\n"
            "}"
        )
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.header)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border: none;\n"
            "   padding-left: 10;\n"
            "   padding-right: 10;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(45, 45, 45);\n"
            "}"
        )
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.header)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border-top-right-radius: 5;\n"
            "   border-bottom-right-radius: 5;\n"
            "   padding-right: 5;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(45, 45, 45);\n"
            "}"
        )
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.header)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(
            "QPushButton {\n"
            "   color: rgb(186, 189, 182);\n"
            "   background-color: rgb(35, 35, 35);\n"
            "   border-radius: 5;\n"
            "   padding-left: 5;\n"
            "   padding-right: 5;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(45, 45, 45);\n"
            "}"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.main_w.addWidget(self.header, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.main_w, 0, 1, 1, 1)
        self.sidebar = QtWidgets.QFrame(self.main_window)
        self.sidebar.setStyleSheet(
            "QFrame {\n" "    background-color: rgb(30, 30, 30);\n" "}\n" ""
        )
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.x = QtWidgets.QPushButton(self.sidebar)
        self.x.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.x.setObjectName("x")
        self.horizontalLayout_7.addWidget(self.x)
        self.s = QtWidgets.QPushButton(self.sidebar)
        self.s.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.s.setObjectName("s")
        self.horizontalLayout_7.addWidget(self.s)
        self.d = QtWidgets.QPushButton(self.sidebar)
        self.d.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.d.setObjectName("d")
        self.horizontalLayout_7.addWidget(self.d)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(15, 10, -1, 30)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_13 = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_5.addWidget(self.pushButton_13)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_5.addItem(spacerItem4)
        self.pushButton_9 = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_9.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_2 = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_5.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_5.addItem(spacerItem6)
        self.pushButton = QtWidgets.QPushButton(self.sidebar)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.pushButton_8 = QtWidgets.QPushButton(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_8.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setStyleSheet(
            "QPushButton {\n"
            "    color: rgb(186, 189, 182);\n"
            "    background-color: rgb(30, 30, 30);\n"
            "    border-top-left-radius: 5;\n"
            "    border-bottom-left-radius: 5;\n"
            "    border-top-right-radius: 5;\n"
            "    border-bottom-right-radius: 5;\n"
            "    padding: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background-color: rgb(40, 40, 40);\n"
            "}"
        )
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_5.addWidget(self.pushButton_8)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout.addWidget(self.sidebar, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.main_window)

        self.retranslateUi(MainWindow)
        self.all_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clear_button.setText(_translate("MainWindow", "clear"))
        __sortingEnabled = self.receiver_list.isSortingEnabled()
        self.receiver_list.setSortingEnabled(False)
        item = self.receiver_list.item(0)
        item.setText(_translate("MainWindow", "New Message"))
        item = self.receiver_list.item(1)
        item.setText(_translate("MainWindow", "New Message"))
        self.receiver_list.setSortingEnabled(__sortingEnabled)
        self.msg_convertor.setText(_translate("MainWindow", "MsgPack"))
        self.msg_convertor_v.setText(_translate("MainWindow", "∇"))
        self.all_button.setText(_translate("MainWindow", "All"))
        self.received_button.setText(_translate("MainWindow", "Received"))
        self.published_button.setText(_translate("MainWindow", "Published"))
        self.pushButton_11.setText(_translate("MainWindow", "Delete"))
        self.pushButton_12.setText(_translate("MainWindow", "Add to Clipboard"))
        self.pushButton_15.setText(_translate("MainWindow", "QoS 0"))
        self.pushButton_16.setText(_translate("MainWindow", "∇"))
        self.pushButton_10.setText(_translate("MainWindow", "Publish"))
        __sortingEnabled = self.command_items.isSortingEnabled()
        self.command_items.setSortingEnabled(False)
        item = self.command_items.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.command_items.setSortingEnabled(__sortingEnabled)
        self.all_tabs.setTabText(
            self.all_tabs.indexOf(self.main_tab), _translate("MainWindow", "Page")
        )
        self.label_9.setText(_translate("MainWindow", "General"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_7.setText(_translate("MainWindow", "SSL/TLS"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.label.setText(_translate("MainWindow", "Client ID"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.label_23.setText(_translate("MainWindow", "Certificate"))
        self.label_22.setText(_translate("MainWindow", "SSL"))
        self.label_3.setText(_translate("MainWindow", "Host"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.radioButton_2.setText(
            _translate("MainWindow", "CA signed server certificate")
        )
        self.radioButton.setText(
            _translate("MainWindow", "CA or Self signed certificate")
        )
        self.label_24.setText(_translate("MainWindow", "Certificates"))
        self.label_25.setText(_translate("MainWindow", "CA File"))
        self.label_26.setText(_translate("MainWindow", "Client Certificate File"))
        self.label_27.setText(_translate("MainWindow", "Client Key File"))
        self.label_8.setText(_translate("MainWindow", "Advanced"))
        self.label_13.setText(_translate("MainWindow", "Auto Reconnect"))
        self.label_18.setText(_translate("MainWindow", "Maximum Packet Size"))
        self.label_19.setText(_translate("MainWindow", "Topic Alias Maximum"))
        self.label_12.setText(_translate("MainWindow", "Keep Alive"))
        self.label_15.setText(_translate("MainWindow", "Clean Start"))
        self.label_16.setText(_translate("MainWindow", "Session Expiry Interval"))
        self.label_11.setText(_translate("MainWindow", "Connect Timeout"))
        self.label_10.setText(_translate("MainWindow", "MQTT Version"))
        self.label_20.setText(_translate("MainWindow", "Request Response"))
        self.label_14.setText(_translate("MainWindow", "Reconnect Period"))
        self.label_21.setText(_translate("MainWindow", "Request Problem Info"))
        self.label_17.setText(_translate("MainWindow", "Receive Maximum"))
        self.all_tabs.setTabText(
            self.all_tabs.indexOf(self.plus_tab), _translate("MainWindow", "plus")
        )
        self.all_tabs.setTabText(
            self.all_tabs.indexOf(self.settings_tab), _translate("MainWindow", "Page")
        )
        self.all_tabs.setTabText(
            self.all_tabs.indexOf(self.info_tab), _translate("MainWindow", "Tab 2")
        )
        self.pushButton_14.setText(_translate("MainWindow", "edit"))
        self.pushButton_6.setText(_translate("MainWindow", "🄰"))
        self.pushButton_5.setText(_translate("MainWindow", "Profile Name"))
        self.pushButton_4.setText(_translate("MainWindow", "∇"))
        self.pushButton_3.setText(_translate("MainWindow", "▶"))
        self.x.setText(_translate("MainWindow", "x"))
        self.s.setText(_translate("MainWindow", "_"))
        self.d.setText(_translate("MainWindow", "e"))
        self.pushButton_13.setText(_translate("MainWindow", "logo"))
        self.pushButton_9.setText(_translate("MainWindow", "main"))
        self.pushButton_2.setText(_translate("MainWindow", "+"))
        self.pushButton.setText(_translate("MainWindow", "stg"))
        self.pushButton_8.setText(_translate("MainWindow", "inf"))
